# TBC爬虫YAML配置文件
CrawlerInfo:
  RecrawlCount: 10
  CrawlerOffset: 135794
  CrawlerCount: 16

CoinType: "TBC"

Fullnode:
  URL: 
    - "tbc:tbc@172.31.40.152:8332"
  ZMQURL:
    - "tcp://172.31.40.152:28333"
  NETTYPE: "simnet"


RedisDbPaths:
  vout: "redis://127.0.0.1:6379/13"

Type: "vout_filter"

LogConfig:
  LogDir: "./logs/simnet/vout.log"
  LogLevel: "INFO"

