# TBC爬虫YAML配置文件
CrawlerInfo:
  RecrawlCount: 10
  CrawlerOffset: 863520
  CrawlerCount: 16

CoinType: "TBC"

Fullnode:
  URL: 
    - "tbc:tbc@172.31.40.152:8332"
  ZMQURL: 
    - "tcp://172.31.40.152:28333"
  NETTYPE: "mainnet"

DbPaths:
# 代币交易信息
  token_tx_hash: "mongodb://admin:metasoftmongodb@127.0.0.1:27017"
  token_tx_hash_pre: "mongodb://admin:metasoftmongodb@127.0.0.1:27017"
  token_tx_block_info: "mongodb://admin:metasoftmongodb@127.0.0.1:27017"
  token_tx: "mongodb://admin:metasoftmongodb@127.0.0.1:27017"
  unconfirm_token_tx: "mongodb://admin:metasoftmongodb@127.0.0.1:27017"
  ft_tx: "mongodb://admin:metasoftmongodb@127.0.0.1:27017"
  error_ft_tx: "mongodb://admin:metasoftmongodb@127.0.0.1:27017"

DbIndexs:
  # Token
  token_tx:
    - "addr"
    - "value.contractid"
    - "value.combinescript"
    - "value.contracthash"
    - "prehash"
    - "preindex"
    - "txid"
  unconfirm_token_tx:
    - "addr"
    - "value.contractid"
    - "value.combinescript"
    - "value.contracthash"
    - "prehash"
    - "preindex"
    - "txid"
  token_tx_block_info:
    - "hash"
  ft_tx:
    - "hash"
  token_tx_hash:
    - "height"
  token_tx_hash_pre:
    - "height"

RedisDbPaths:
  vout: "redis://127.0.0.1:6379/13"
  
Type: "tokentx_filter"

LogConfig:
  LogDir: "./logs/mainnet/tokentx.log"
  LogLevel: "INFO"

